### ISSUE TITLE
PaaS开发者中心中SaaS可见范围偶发报错

### ISSUE THREAD

**Issue by pagezz-canway** [TencentBlueKing/legacy-bk-paas#1059]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
BUG反馈

**PaaS/PaaSAgent版本(The versions used):**

PaaS 平台 | open_paas | 2.12.49
PaaS Agent | paas_agent | 2.6.3
PaaS Plugins | paas_plugins | 2.5.4

**发生了什么(What happened):**
开发者中心，SaaS可见范围选择，在进行组织展开时，有一定概率出现转圈。对应的接口返回正常，控制台报错
<img width="825" alt="image" src="https://user-images.githubusercontent.com/8849151/212250204-d58e570b-c2b0-4d46-b534-86adf38308e5.png">

报错信息：
Uncaught ReferenceError: USER_LIST_CALLBACK1673589898964 is not defined
    at ?app_code=bk-magicbox&no_page=true&lookup_field=parent&exact_lookups=3&callback=USER_LIST_CALLBACK1673589898964:1:1

<img width="1068" alt="image" src="https://user-images.githubusercontent.com/8849151/212250315-f57e1760-1b65-4e72-a2ae-f34543f17e6e.png">

**期望是什么(What you expected to happen):**
正常展开组织架构并可选择

**如何复现(How to reproduce it):**
多尝试几次选择不同的组织

**相关的日志详情(访问日志及应用日志: paas.log/login.log/esb.log/esb_api.log)和截图等(Log & Screenshot):**

**备注(Anything else we need to know):**

**Comment by wklken** [comment]
多套环境验证未复现

这里前端用的jsonp协议
请求参数: `&callback=USER_LIST_CALLBACK1675071307978`
响应体: `USER_LIST_CALLBACK1675071307978({})`

**Comment by wklken** [comment]
看着像这个
> The server is giving back the JSONP resource using the wrong callback function name.

https://stackoverflow.com/questions/33366992/ajax-with-jsonp-returns-error-callback-is-undefined

需要在能复现的环境, 手工拼接请求验证是否是 esb 服务端的问题, 即验证请求的`callback=A`是响应体中的 `A()`, 如果不是就会报issue中的这个错误

**Comment by wklken** [comment]
<img width="1825" alt="image" src="https://user-images.githubusercontent.com/2002216/215685400-84eeddb9-4972-434c-a89a-42cc46ec1c38.png">

**Comment by wklken** [comment]
2.14.44
