### ISSUE TITLE
PaaS源码下载问题

### ISSUE THREAD

**Issue by LinDeshuang** [TencentBlueKing/legacy-bk-paas#1060]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
需求提交

**PaaS/PaaSAgent版本(The versions used):**
蓝鲸版本：6.1.1-beta1
PaaS版本：2.14.8
PaaSAgent版本：3.2.4

**发生了什么(What happened):**
根据PaaS版本在release中找到对应版本的源码下载后，发现没有apigw的源码，其他如login、esb等的源码都有，这个是正常的吗？

**期望是什么(What you expected to happen):**
请问如何找到蓝鲸版本对应的PaaS版本源码？

**Comment by wklken** [comment]
apigw源码没有开源, 因为是legacy 版本的;
-----

最新版蓝鲸容器化版本带的是 PaaSV3以及新版本的apigateway
