### ISSUE TITLE
开发者中心查询日志带正斜杠的字符串，精确查找可以找到，模糊查找反而为空

### ISSUE THREAD

**Issue by pagezz-canway** [TencentBlueKing/legacy-bk-paas#1067]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
BUG反馈

**PaaS/PaaSAgent版本(The versions used):**
open_paas | 2.14.33
paas_agent | 2.6.4
paas_plugins | 2.5.4

**发生了什么(What happened):**
开发者中心查询日志带正斜杠的字符串，精确查找可以找到，模糊查找反而为空

**期望是什么(What you expected to happen):**
模糊查找的查询结果大于精确查找

**如何复现(How to reproduce it):**
进入标准运维SaaS的日志查询页面，搜索关键字为”/taskflow/api“，精确查找有结果
![image](https://user-images.githubusercontent.com/8849151/227874715-7a75d187-686e-4cc1-90d5-4c9296dda8d8.png)
去掉精确查找，结果为空
![image](https://user-images.githubusercontent.com/8849151/227875020-3e4a205f-1b03-4adc-bc92-e9372a006f65.png)

**相关的日志详情(访问日志及应用日志: paas.log/login.log/esb.log/esb_api.log)和截图等(Log & Screenshot):**

**备注(Anything else we need to know):**

**Comment by wklken** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#query-string-syntax
