### ISSUE TITLE
PIP包需要更新，以便适配麒麟V10操作系统和ARM架构

### ISSUE THREAD

**Issue by pagezz-canway** [TencentBlueKing/legacy-bk-paas#1072]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
BUG反馈

**PaaS/PaaSAgent版本(The versions used):**
最新版

**发生了什么(What happened):**
pip包不兼容麒麟V10操作系统和ARM架构

**期望是什么(What you expected to happen):**
gevent==1.5.0 升级为 gevent==22.10.2
uWSGI==2.0.13.1 升级为 uWSGI==2.0.18

**如何复现(How to reproduce it):**

**相关的日志详情(访问日志及应用日志: paas.log/login.log/esb.log/esb_api.log)和截图等(Log & Screenshot):**

**备注(Anything else we need to know):**

**Comment by wklken** [comment]
之前尝试过升gevent版本, 会由于依赖问题导致出包失败(python/django及其他依赖包有冲突)

-----------

不建议在通用版本里面做这个升级, 成本比较大, 并且需要做完整测试; 建议在专有系统分发包做处理(之前麒麟的都是独立做这个处理的)

**Comment by wklken** [comment]
麒麟的分发包中由于uwsgi的问题, 后来定制改成了gunicorn启动

**Comment by pagezz-canway** [comment]
OK
