### ISSUE TITLE
开启登录加密后，多次点击登录按钮时登录失败

### ISSUE THREAD

**Issue by linxiaowu1992** [TencentBlueKing/legacy-bk-paas#1121]
**是`BUG反馈`还是`需求提交`(Is this a BUG REPORT or FEATURE REQUEST)?** (choose one):
bug

**PaaS/PaaSAgent版本(The versions used):**
2.14

**发生了什么(What happened):**
用户登录，连续2次点击登录的时候就会提示系统异常:
![image](https://github.com/TencentBlueKing/legacy-bk-paas/assets/29301212/dc3ef751-7cf0-42e6-93f4-1e6fc917c551)
原因为 每次点击登录按钮都会加密一次，第一次点击后已经加密，并把输入框的密码置为加密后的字符串；快速点击第二次，会继续对加密后的字符串再加密一次，导致该问题。

**期望是什么(What you expected to happen):**

**如何复现(How to reproduce it):**

**相关的日志详情(访问日志及应用日志: paas.log/login.log/esb.log/esb_api.log)和截图等(Log & Screenshot):**

**备注(Anything else we need to know):**

**Comment by linxiaowu1992** [comment]
解决方式：点击一次登录后，按钮可以置为不可点击状态。

**Comment by linxiaowu-canway** [comment]
2.14.65已修复
